### ISSUE TITLE
Show filenames produced by --with-filename

### ISSUE THREAD

**Issue by Bill** [protocool/ack-tmbundle#1]
I'm successfully using a .ackrc to specify for instance:

```
--type-add
css=sass
```

However, the bundle seems to swallow filenames produced by:

```
--with-filename
```

When the result list is long, having filenames to break things up would be real valuable.

**Comment by protocool** [comment]
The bundle has been written to handle grouped output from ack. Each filename group gets a heading that displays the name of the file.

If you want to display the filename beside each match you'll have to rewrite a fair chunk of the output formatting code, but it shouldn't be tricky or anything.

**Comment by Bill** [comment]
Oh wow. You know what my problem was. I am using the "shiny" theme in TextMate. In that theme, the filenames are invisible! Switching to e.g. "default" solves the problem. Thanks for the hint!!

PS I was able to switch the theme on the Ack results panel (drop down) and it did not affect the theme used on the app's main screen (good).

**Comment by protocool** [comment]
Cool, thanks for letting me know :-)
