### ISSUE TITLE
Running Lion, will not use .ackrc file

### ISSUE THREAD

**Issue by clepore** [protocool/ack-tmbundle#4]
I'm running the ack bundle for textmate and I have the ~/.ackrc file with "--type-add=ruby=.haml,.rake,.rsel" inside of it and I cannot get the bundle to search my .haml files. I have the advanced option enable to "load defaults by .ackrc" and it still doesn't work. Any ideas?

**Comment by bblimke** [comment]
Same problem here. Have you found any workaround?

**Comment by clepore** [comment]
I changed jobs and now work mostly with php and html. So far that was the only thing I could figure out and its working well lol (I dont necessarily recommend it). Other than that, let me know if you figure it out, it'll help with side projects.

**Comment by bblimke** [comment]
I switched to https://github.com/protocool/AckMate which allows you to search in selected folder if you press command-return to seach.

**Comment by hackingbeauty** [comment]
ack-tmbundle doesn't work with Mountain Lion.  For any version of Mac OS greater than 10.5, use AckMate (https://github.com/protocool/AckMate).
- download the AckMate zip here and install the dmg: https://github.com/protocool/AckMate/downloads
- tweak ur .ackrc
- after relaunching TextMate press ctrl-option-command-f, or specify your own keyboard shortcut, to launch AckMate
